# Generated by Django 4.2.11 on 2024-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOption',
            fields=[
                ('CodeID', models.AutoField(primary_key=True, serialize=False)),
                ('CodeTypeID', models.CharField(max_length=3)),
                ('CodeTypeName', models.CharField(max_length=100)),
                ('CodeDataID', models.CharField(max_length=3)),
                ('CodeDataName', models.CharField(max_length=100)),
                ('CodeNote', models.CharField(blank=True, max_length=100, null=True)),
                ('UseYN', models.CharField(max_length=1)),
                ('Created_date', models.DateTimeField()),
                ('Modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
