# Generated by Django 4.2.11 on 2024-05-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('ClusterID', models.AutoField(primary_key=True, serialize=False)),
                ('ClusterName', models.CharField(max_length=100)),
                ('SERVER_TYPE1', models.CharField(max_length=3)),
                ('SERVER_TYPE2', models.CharField(max_length=3)),
                ('SERVER_TYPE3', models.CharField(max_length=3)),
                ('Created_date', models.DateTimeField()),
                ('Modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
