# Generated by Django 4.2.11 on 2024-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('HostID', models.AutoField(primary_key=True, serialize=False)),
                ('HostName', models.CharField(max_length=100)),
                ('ClusterID', models.IntegerField()),
                ('Gen', models.CharField(max_length=3)),
                ('Model', models.CharField(max_length=100)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('CPU_Model', models.CharField(max_length=100)),
                ('Core', models.IntegerField()),
                ('Memory', models.IntegerField()),
                ('vSANDISK', models.IntegerField(blank=True, null=True)),
                ('GPUMem', models.IntegerField(blank=True, null=True)),
                ('EOS_Date', models.DateTimeField(blank=True, null=True)),
                ('Created_date', models.DateTimeField()),
                ('Modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
