# Generated by Django 4.2.11 on 2024-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('StorageID', models.AutoField(primary_key=True, serialize=False)),
                ('StorageName', models.CharField(max_length=100)),
                ('Gen', models.CharField(max_length=3)),
                ('Model', models.CharField(max_length=100)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('FuncType', models.CharField(max_length=10)),
                ('Size', models.IntegerField()),
                ('EOS_Date', models.DateTimeField(blank=True, null=True)),
                ('Created_date', models.DateTimeField()),
                ('Modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
